spring:
  rabbitmq:
    addresses: ${vcap.services.${PREFIX:}rabbitmq.credentials.uri:amqp://${RABBITMQ_HOST:172.18.0.3}:${RABBITMQ_PORT:5672}}
   
zuul:
  add-host-header: true
  ignore-security-headers: false
  sensitiveHeaders:
  prefix: /api
  ignored-services: '*'
  routes:
    security-server:
      path: /oauth/**
      serviceId: OAUTH-SERVER
      stripPrefix: false
    ms-coosalud-visita:
      path: /ms-coosalud-visita/v1/**
      serviceId: MS-COOSALUD-VISITA
      stripPrefix: false
    ms-coosalud-persona:
      path: /ms-coosalud-persona/v1/**
      serviceId: MS-COOSALUD-PERSONA
      stripPrefix: false
    ms-coosalud-grpfamiliar:
      path: /ms-coosalud-grpfamiliar/v1/**
      serviceId: MS-COOSALUD-GRPFAMILIAR
      stripPrefix: false
    ms-coosalud-consmed:
      path: /ConsultaMedica/v1/**
      serviceId: MS-COOSALUD-CONSMED
      stripPrefix: false
    ms-coosalud-visita-dom:
      path: /MedicionSaludFamiliarRN/v1/**
      serviceId: MS-COOSALUD-VISITA-DOM
      stripPrefix: false
    ms-coosalud-saludfamiliar:
      path: /MedicionSaludFamiliar/v1/**
      serviceId: MS-COOSALUD-SALUDFAMILIAR
      stripPrefix: false
    ms-coosalud-vivienda:
      path: /ms-coosalud-vivienda/v1/**
      serviceId: MS-COOSALUD-VIVIENDA
      stripPrefix: false
    ms-coosalud-vacuna:
      path: /ms-coosalud-vacuna/v1/**
      serviceId: MS-COOSALUD-VACUNA
      stripPrefix: false
    ms-coosalud-remision:
      path: /ms-coosalud-remision/v1/**
      serviceId: MS-COOSALUD-REMISION
      stripPrefix: false
    ms-coosalud-bebe:
      path: /ms-coosalud-bebe/v1/**
      serviceId: MS-COOSALUD-BEBE
      stripPrefix: false
    ms-coosalud-adolecente:
      path: /ms-coosalud-adolecente/v1/**
      serviceId: MS-COOSALUD-ADOLECENTE
      stripPrefix: false
    ms-coosalud-adulto:
      path: /ms-coosalud-adulto/v1/**
      serviceId: MS-COOSALUD-ADULTO
      stripPrefix: false
    ms-coosalud-mujer:
      path: /ms-coosalud-mujer/v1/**
      serviceId: MS-COOSALUD-MUJER
      stripPrefix: false
    ms-coosalud-nino:
      path: /ms-coosalud-nino/v1/**
      serviceId: MS-COOSALUD-NINO
      stripPrefix: false
    ratelimit:
      enabled: false
      repository: IN_MEMORY
      behind-proxy: true
      default-policy: #optional - will apply unless specific policy exists
        limit: 20 #optional - request number limit per refresh interval window
        quota: 1000 #optional - request time limit per refresh interval window (in seconds)
        refresh-interval: 60 #default value (in seconds)
    
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
  
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 60000
  eureka:
    enabled: true   
  eager-load:
    enabled: false
    
security:
  basic:
    enabled: false
  user:
    name: zuul
    password: a39WqtRWAaXhckj
    role: ADMIN

logging:  
#  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud.netflix.zuul: 'DEBUG'
    org.springframework.cloud.netflix.ribbon: 'DEBUG'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'
